site_name: Test Website

repo_name: 'PGxAfrica.github.io'
repo_url: https://github.com/PGxAfrica/PGxAfrica.github.io


nav:
  - index.md
  - about.md
  - people.md


theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.tabs.sticky