site_name: Test Website

repo_name: 'PGxAfrica.github.io'
repo_url: https://github.com/PGxAfrica/PGxAfrica.github.io


nav:
  - Home: 'index.md'
  - About: 'about.md'
  - People: 'people.md'


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - toc:
      permalink: true